name: Generate binary filename
on:
  workflow_call:
    inputs:
      original_event_name:
        required: true
        type: string
    outputs:
      filename:
        value: ${{ jobs.filename.outputs.filename }}

jobs:
  filename:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.name }}
      hash: ${{ steps.hash.outputs.name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Using the CMakeLists version
        if: inputs.original_event_name != 'pull_request'
        id: version
        run: echo "name=sdl2dsu-$(grep -E "\s+VERSION" CMakeLists.txt | xargs | cut -d' ' -f 2)-x86_64" >> $GITHUB_OUTPUT

      - name: Using the commit SHA as a version
        if: inputs.original_event_name != 'pull_request'
        id: hash
        run: echo "name=sdl2dsu-$(git rev-parse --short \"${{ github.sha }}\")-x86_64" >> $GITHUB_OUTPUT

      - name: Print the filename base
        run: echo "${{ steps.version.outputs.name }}${{ steps.hash.outputs.name }}"